### ISSUE TITLE
Can't locate object method "new" via package "String::Interpolate::Named"

### ISSUE THREAD

**Issue by eserte** [ikluft/WebFetch#1]
On some of my smokers the test suite fails like this:
```
Can't locate object method "new" via package "String::Interpolate::Named" at t/020-sitenews.t line 309.
# Looks like your test exited with 2 just after 12.
t/020-sitenews.t .......... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 61/73 subtests 
```

According to the test report summary, String::Interpolate::Named is installed here, but only with version 0.05, which might be too low. So if this is the case, the minimum prereq version should be adjusted.

**Comment by ikluft** [comment]
I updated the test script to be compatible with the older 0.05 version of String::Interpolate::Named. This is in WebFetch 0.15.3.
